Repository MathysC/La-Guidonette, pull requests merged in 2023-09, with the labels that each got.

#5 [FEATURE] Add CI-CD Pipelines
  .devcontainer/Dockerfile
  .devcontainer/devcontainer.json
  .github/workflows/CD.yml
  .github/workflows/CI.yml
  .vscode/settings.json
  .yo-rc.json
  Procfile
  README-DOCKER-COMPOSE.md
  docker-compose.yml
  docs/badges/branches.svg
  docs/badges/jacoco.svg
  pom.xml
  src/main/docker/app.yml
  src/main/docker/docker-registry.yml
  src/main/resources/config/application-heroku.yml
  src/main/resources/config/bootstrap-heroku.yml
  system.properties
Labels: enhancement

#13 [BUGFIX]: Remove CI workflow
  .github/workflows/CI.yml
  .gitignore
  docs/badges/branches.svg
  docs/badges/jacoco.svg
Labels: bug

#22 Feature/home page
  src/main/webapp/app/app.module.ts
  src/main/webapp/app/cart-content.service.ts
  src/main/webapp/app/cart/cart.component.html
  src/main/webapp/app/cart/cart.component.ts
  src/main/webapp/app/entities/dto/GetProductPageResponseDto.ts
  src/main/webapp/app/entities/product/service/product.service.ts
  src/main/webapp/app/layouts/main/main.component.html
  src/main/webapp/app/layouts/product-card/product-card.component.html
  src/main/webapp/app/layouts/product-card/product-card.component.scss
  src/main/webapp/app/layouts/product-card/product-card.component.ts
  src/main/webapp/app/list-products/list-products.component.html
  src/main/webapp/app/list-products/list-products.component.scss
  src/main/webapp/app/list-products/list-products.component.ts
  src/main/webapp/app/list-products/list-products.module.ts
  src/main/webapp/app/list-products/product.ts
  src/main/webapp/app/order/order.component.html
  src/main/webapp/app/order/order.component.ts
  src/main/webapp/content/scss/global.scss
Labels: enhancement

#23 [BUGFIX]: add liquibase version in pom
  pom.xml
  src/main/webapp/app/app-routing.module.ts
Labels: bug

#30 [FEATURE] front end product page
  src/main/java/fr/uga/laguidonette/config/SecurityConfiguration.java
  src/main/webapp/app/app-routing.module.ts
  src/main/webapp/app/app.module.ts
  src/main/webapp/app/layouts/product-card/product-card.component.html
  src/main/webapp/app/layouts/product-card/product-card.module.ts
  src/main/webapp/app/product-page/product-page.component.html
  src/main/webapp/app/product-page/product-page.component.scss
  src/main/webapp/app/product-page/product-page.component.spec.ts
  src/main/webapp/app/product-page/product-page.component.ts
  src/main/webapp/app/product-page/product-page.module.ts
  src/main/webapp/app/product-page/product-page.route.ts
  src/main/webapp/app/services/cart-content.service.ts
Labels: enhancement

#27 [FEATURE] Add image storing service
  .gitignore
  .husky/pre-commit
  .jhipster/Product.json
  angular.json
  mvnw
  npmw
  package-lock.json
  package.json
  src/main/java/fr/uga/laguidonette/config/SecurityConfiguration.java
  src/main/java/fr/uga/laguidonette/domain/Product.java
  src/main/java/fr/uga/laguidonette/service/impl/ProductServiceImpl.java
  src/main/resources/config/liquibase/changelog/20230909074810_added_entity_Product.xml
  src/main/resources/config/liquibase/fake-data/product.csv
  src/main/webapp/app/entities/product/detail/product-detail.component.html
  src/main/webapp/app/entities/product/list/product.component.html
  src/main/webapp/app/entities/product/product.model.ts
  src/main/webapp/app/entities/product/product.test-samples.ts
  src/main/webapp/app/entities/product/update/product-form.service.spec.ts
  src/main/webapp/app/entities/product/update/product-form.service.ts
  src/main/webapp/app/entities/product/update/product-update.component.html
  src/main/webapp/app/layouts/navbar/navbar.component.html
  src/main/webapp/app/layouts/product-card/product-card.component.html
  src/main/webapp/app/layouts/product-card/product-card.module.ts
  src/main/webapp/app/layouts/product-image/product-image.component.html
  src/main/webapp/app/layouts/product-image/product-image.component.scss
  src/main/webapp/app/layouts/product-image/product-image.component.spec.ts
  src/main/webapp/app/layouts/product-image/product-image.component.ts
  src/main/webapp/app/services/aws/s3.service.spec.ts
  src/main/webapp/app/services/aws/s3.service.ts
  src/main/webapp/environments/environment.development.ts
  src/main/webapp/i18n/en/product.json
  src/test/java/fr/uga/laguidonette/web/rest/ProductResourceIT.java
Labels: enhancement

#29 [BUGFIX]:No price in product card
  src/main/webapp/app/layouts/product-card/product-card.component.html
  src/main/webapp/app/layouts/product-card/product-card.component.scss
  src/main/webapp/app/layouts/product-card/product-card.module.ts
Labels: enhancement

#60 [FEATURE] Display order's stock
  src/main/webapp/app/cart/cart.component.html
  src/main/webapp/app/entities/dto/CoupleProductQuantity.ts
  src/main/webapp/app/post-cart/order/order.component.html
  src/main/webapp/app/post-cart/order/order.component.ts
  src/main/webapp/app/post-cart/order/order.module.ts
  src/main/webapp/app/post-cart/post-cart.component.html
  src/main/webapp/app/services/cart-content.service.ts
Labels: documentation, enhancement

#58 [FEATURE] Add vscode tasks
  .vscode/tasks.json
  angular.json
Labels: enhancement

#61 [FEATURE] Products on homepage and search
  src/main/java/fr/uga/laguidonette/repository/ProductRepository.java
  src/main/java/fr/uga/laguidonette/service/ProductService.java
  src/main/java/fr/uga/laguidonette/service/impl/ProductServiceImpl.java
  src/main/java/fr/uga/laguidonette/web/rest/ProductResource.java
  src/main/webapp/app/app-routing.module.ts
  src/main/webapp/app/app.module.ts
  src/main/webapp/app/entities/category/detail/category-detail.component.html
  src/main/webapp/app/entities/category/list/category.component.html
  src/main/webapp/app/entities/order-line/detail/order-line-detail.component.html
  src/main/webapp/app/entities/order-line/list/order-line.component.html
  src/main/webapp/app/entities/product/detail/product-detail.component.html
  src/main/webapp/app/entities/product/list/product.component.html
  src/main/webapp/app/entities/product/service/product.service.ts
  src/main/webapp/app/entities/torder/detail/torder-detail.component.html
  src/main/webapp/app/entities/torder/list/torder.component.html
  src/main/webapp/app/home/home.component.html
  src/main/webapp/app/home/home.component.ts
  src/main/webapp/app/home/home.module.ts
  src/main/webapp/app/home/home.route.ts
  src/main/webapp/app/layouts/navbar/navbar.component.html
  src/main/webapp/app/list-products/list-products.component.html
  src/main/webapp/app/list-products/list-products.component.ts
  src/main/webapp/app/list-products/list-products.module.ts
  src/main/webapp/app/list-products/list-products.route.ts
  src/main/webapp/app/search/search/search.component.html
  src/main/webapp/app/search/search/search.component.scss
  src/main/webapp/app/search/search/search.component.spec.ts
  src/main/webapp/app/search/search/search.component.ts
  src/main/webapp/app/search/search/search.module.ts
  src/main/webapp/app/search/search/search.route.ts
  src/main/webapp/app/search/service/search-service.spec.ts
  src/main/webapp/app/search/service/search-service.ts
Labels: enhancement

#72 [FEATURE] Account page
  src/main/webapp/app/account/account.module.ts
  src/main/webapp/app/account/account.route.ts
  src/main/webapp/app/account/register/register.component.html
  src/main/webapp/app/account/user-page/user-page.component.html
  src/main/webapp/app/account/user-page/user-page.component.scss
  src/main/webapp/app/account/user-page/user-page.component.ts
  src/main/webapp/app/account/user-page/user-page.route.ts
  src/main/webapp/app/app-routing.module.ts
  src/main/webapp/app/app.module.ts
  src/main/webapp/app/cart/cart.route.ts
  src/main/webapp/app/layouts/navbar/navbar.component.html
  src/main/webapp/app/layouts/navbar/navbar.component.scss
  src/main/webapp/app/layouts/navbar/navbar.component.ts
  src/main/webapp/app/list-products/list-products.route.ts
  src/main/webapp/app/pocket-login/pocket-login.component.html
  src/main/webapp/app/pocket-login/pocket-login.component.scss
  src/main/webapp/app/pocket-login/pocket-login.component.ts
  src/main/webapp/app/pocket-login/pocket-login.module.ts
  src/main/webapp/app/pocket-login/pocket-login.route.ts
  src/main/webapp/app/product-page/product-page.component.ts
  src/main/webapp/app/product-page/product-page.route.ts
  src/main/webapp/i18n/en/cart.json
  src/main/webapp/i18n/en/global.json
  src/main/webapp/i18n/en/list-products.json
  src/main/webapp/i18n/en/product-page.json
Labels: bug, enhancement
